# Generated by Django 5.0.4 on 2024-05-06 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tableemployee',
            old_name='pin',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='tableemployee',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('HR', 'HR'), ('Sales', 'Sales'), ('Management', 'Management')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
