# Generated by Django 5.0.4 on 2024-05-06 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_pin_tableemployee_phone_tableemployee_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeesPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.CharField(max_length=50)),
                ('notes', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tableemployee')),
            ],
        ),
    ]
