# Generated by Django 5.0.4 on 2024-05-07 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_employeesperformance'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='password',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
