# Generated by Django 5.0.4 on 2024-05-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_tableemployee_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableemployee',
            name='phone',
            field=models.IntegerField(unique=True),
        ),
    ]
