# Generated by Django 5.0.4 on 2024-05-08 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_teammember'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='Admin_Name',
            new_name='Admin_id',
        ),
        migrations.RenameField(
            model_name='teammember',
            old_name='Member_Name',
            new_name='Member_id',
        ),
        migrations.AlterField(
            model_name='tableemployee',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('HR', 'HR'), ('Sales', 'Sales'), ('Management', 'Management'), ('Team_Member', 'Team_Member')], max_length=50),
        ),
    ]
