# Generated by Django 5.0.4 on 2024-05-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_admin_name_teammember_admin_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TL_id', models.CharField(max_length=50)),
                ('MB_id', models.CharField(max_length=50)),
                ('Work_Quality', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=50)),
                ('Work_Quantity', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=50)),
                ('Work_Skills', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=50)),
                ('Team_Work', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=50)),
                ('Achivements', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=50)),
                ('Overall_Report', models.CharField(max_length=50)),
                ('Remarks', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='EmployeesPerformance',
        ),
    ]
