# Generated by Django 5.0.4 on 2024-05-10 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_empperformance_delete_employeesperformance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.RenameField(
            model_name='empperformance',
            old_name='MB_id',
            new_name='Member_id',
        ),
        migrations.RenameField(
            model_name='empperformance',
            old_name='TL_id',
            new_name='TeamLeader_id',
        ),
        migrations.RenameField(
            model_name='teammember',
            old_name='Admin_id',
            new_name='TeamLeader_id',
        ),
    ]
