# Generated by Django 5.0.4 on 2024-05-11 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_delete_person_rename_mb_id_empperformance_member_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empperformance',
            name='TeamLeader_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tableemployee'),
        ),
    ]
