# Generated by Django 5.0.4 on 2024-05-11 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_empperformance_teamleader_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empperformance',
            name='Member_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tableemployee'),
        ),
        migrations.AlterField(
            model_name='empperformance',
            name='TeamLeader_id',
            field=models.CharField(max_length=50),
        ),
    ]
